project_id = "ted"

[api]
enabled = true
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
major_version = 15

[studio]
enabled = true

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["http://localhost:3000/admin/auth/callback"]
jwt_expiry = 3600
enable_signup = true

[storage]
enabled = true
file_size_limit = "200MiB"
