import { Badge, EmptyState, PageHeader, Panel } from "@/components/ui";
import { VaultUploader } from "@/components/vault-uploader";
import { requirePunter } from "@/lib/auth/punter";
import { createServiceSupabase } from "@/lib/supabase/service";
import { submitStoryAction } from "./actions";

export default async function VaultPage() {
  const { supabase } = await requirePunter(); const { data: items } = await supabase.from("vault_items_public").select("*").order("created_at", { ascending: false });
  const service = createServiceSupabase();
  const media = await Promise.all((items || []).map(async (item) => { if (!item.storage_path) return { ...item, signedUrl: null }; const options = item.kind === "photo" ? { transform: { width: 960, quality: 75 } } : undefined; const { data } = await service.storage.from("vault").createSignedUrl(item.storage_path, 3600, options); return { ...item, signedUrl: data?.signedUrl || null }; }));
  return <div className="grid gap-8"><PageHeader eyebrow="Evidence room" title="The vault" intro="Upload the photos, videos, and stories Ted would rather you forgot. Everything waits for groomsman approval." /><div className="grid gap-5 lg:grid-cols-2"><Panel><h2 className="display text-2xl">Upload evidence</h2><div className="mt-5"><VaultUploader /></div></Panel><Panel><h2 className="display text-2xl">Tell a story</h2><form action={submitStoryAction} className="mt-5 grid gap-4"><label className="label">The story<textarea className="field min-h-36" name="story_text" required maxLength={5000} /></label><div className="grid gap-4 sm:grid-cols-2"><label className="label">Short title<input className="field" name="caption" maxLength={300} /></label><label className="label">Era<input className="field" name="era_tag" maxLength={80} /></label></div><label className="surface-flat flex items-center gap-3 p-4"><input type="checkbox" name="is_anonymous" /> Anonymous to the crew</label><button className="button button-primary justify-self-start">Send story</button></form></Panel></div><section><h2 className="display mb-5 text-3xl">Approved evidence</h2>{media.length ? <div className="columns-1 gap-4 sm:columns-2 lg:columns-3">{media.map((item) => <article key={item.id} className="surface mb-4 break-inside-avoid overflow-hidden">{item.signedUrl && item.kind === "photo" ? <img src={item.signedUrl} alt={item.caption || "Vault photo"} className="h-auto w-full" /> : null}{item.signedUrl && item.kind === "video" ? <video src={item.signedUrl} controls preload="metadata" className="w-full" /> : null}<div className="p-4">{item.era_tag ? <Badge tone="gold">{item.era_tag}</Badge> : null}{item.caption ? <h3 className="display mt-3 text-xl">{item.caption}</h3> : null}{item.story_text ? <p className="mt-3 whitespace-pre-wrap leading-7 text-[var(--chalk-muted)]">{item.story_text}</p> : null}<p className="mt-4 text-xs text-[var(--chalk-muted)]">Added by {item.attribution}</p></div></article>)}</div> : <EmptyState title="Nothing in the vault yet.">Be the first to embarrass him.</EmptyState>}</section></div>;
}
