import { Badge, EmptyState, PageHeader } from "@/components/ui";
import { requireAdmin } from "@/lib/auth/admin";
import { createServiceSupabase } from "@/lib/supabase/service";
import { moderateVaultAction } from "./actions";

export default async function AdminVaultPage() {
  const { supabase } = await requireAdmin(); const { data: items } = await supabase.from("vault_items").select("*,punters(display_name)").eq("moderation_status", "pending").order("created_at"); const service = createServiceSupabase();
  const queue = await Promise.all((items || []).filter((item) => !item.storage_path || item.upload_confirmed_at).map(async (item) => { if (!item.storage_path) return { ...item, signedUrl: null }; const { data } = await service.storage.from("vault").createSignedUrl(item.storage_path, 900); return { ...item, signedUrl: data?.signedUrl || null }; }));
  return <div className="grid gap-8"><PageHeader eyebrow="Moderation room" title="Vault queue" intro="Nothing reaches the crew until a groomsman approves it. Anonymous still means traceable here." />{queue.length ? <div className="grid gap-5 sm:grid-cols-2">{queue.map((item) => <article key={item.id} className="surface overflow-hidden">{item.signedUrl && item.kind === "photo" ? <img src={item.signedUrl} alt="Pending vault item" className="max-h-96 w-full object-contain bg-black/30" /> : null}{item.signedUrl && item.kind === "video" ? <video src={item.signedUrl} controls className="max-h-96 w-full bg-black/30" /> : null}<div className="p-5"><div className="flex flex-wrap gap-2"><Badge tone="neutral">{item.kind}</Badge>{item.is_anonymous ? <Badge tone="signal">Anonymous to crew</Badge> : null}{item.era_tag ? <Badge tone="gold">{item.era_tag}</Badge> : null}</div><h2 className="display mt-4 text-2xl">{item.caption || "Untitled evidence"}</h2>{item.story_text ? <p className="mt-3 whitespace-pre-wrap leading-7 text-[var(--chalk-muted)]">{item.story_text}</p> : null}<p className="mt-4 text-xs text-[var(--chalk-muted)]">Submitted by {(item.punters as unknown as { display_name?: string } | null)?.display_name || "Unknown"}</p><form action={moderateVaultAction} className="mt-5 flex flex-wrap items-center gap-3"><input type="hidden" name="id" value={item.id} /><label className="surface-flat flex items-center gap-2 px-3 py-2 text-xs"><input type="checkbox" name="cleared_for_slideshow" /> Slideshow cleared</label><button className="button button-primary" name="status" value="approved">Approve</button><button className="button button-danger" name="status" value="rejected">Reject</button></form></div></article>)}</div> : <EmptyState title="The queue is clear.">Either everyone is behaving or nobody has found the good photos yet.</EmptyState>}</div>;
}
