import { Badge, PageHeader, Panel } from "@/components/ui";
import { requireAdmin } from "@/lib/auth/admin";
import { EVENT_TZ } from "@/lib/config";
import { toDateTimeLocal } from "@/lib/time";
import { addItineraryAction, deleteItineraryAction, updateItineraryAction } from "./actions";

const Fields = ({ item }: { item?: Record<string, unknown> }) => <><label className="label sm:col-span-2">Title<input className="field" name="title" required defaultValue={String(item?.title || "")} /></label><label className="label">Starts in {EVENT_TZ}<input className="field" type="datetime-local" name="starts_at" required defaultValue={item?.starts_at ? toDateTimeLocal(String(item.starts_at)) : ""} /></label><label className="label">Ends in {EVENT_TZ}<input className="field" type="datetime-local" name="ends_at" defaultValue={item?.ends_at ? toDateTimeLocal(String(item.ends_at)) : ""} /></label><label className="label">Location<input className="field" name="location_name" defaultValue={String(item?.location_name || "")} /></label><label className="label">Address<input className="field" name="address" defaultValue={String(item?.address || "")} /></label><label className="label sm:col-span-2">Description<textarea className="field min-h-24" name="description" defaultValue={String(item?.description || "")} /></label><label className="label">Map URL<input className="field" name="map_url" type="url" defaultValue={String(item?.map_url || "")} /></label><label className="label">Cost note<input className="field" name="cost_note" defaultValue={String(item?.cost_note || "")} /></label><label className="label">Sort order<input className="field mono" name="sort_order" type="number" defaultValue={Number(item?.sort_order || 0)} /></label><label className="surface-flat flex items-center gap-3 p-3"><input name="is_published" type="checkbox" defaultChecked={Boolean(item?.is_published)} /> Published to punters</label></>;

export default async function AdminItineraryPage() {
  const { supabase } = await requireAdmin(); const { data: items } = await supabase.from("itinerary_items").select("*").order("starts_at");
  return <div className="grid gap-8"><PageHeader eyebrow="Fixture secretary" title="Itinerary" intro={`Author every time in ${EVENT_TZ}. Drafts remain invisible until the publish box is checked.`} /><Panel><h2 className="display text-2xl">Add an item</h2><form action={addItineraryAction} className="mt-5 grid gap-4 sm:grid-cols-2"><Fields /><button className="button button-primary sm:col-span-2 sm:justify-self-start">Add itinerary item</button></form></Panel><div className="grid gap-4">{(items || []).map((item) => <details key={item.id} className="surface p-5"><summary className="flex cursor-pointer list-none items-center justify-between gap-4"><div><strong className="display text-xl">{item.title}</strong><p className="mono mt-1 text-xs text-[var(--chalk-muted)]">{toDateTimeLocal(item.starts_at)} {EVENT_TZ}</p></div><Badge tone={item.is_published ? "success" : "neutral"}>{item.is_published ? "Published" : "Draft"}</Badge></summary><form action={updateItineraryAction} className="mt-5 grid gap-4 border-t border-white/10 pt-5 sm:grid-cols-2"><input type="hidden" name="id" value={item.id} /><Fields item={item} /><button className="button button-primary sm:col-span-2 sm:justify-self-start">Save item</button></form><form action={deleteItineraryAction} className="mt-3 flex justify-end"><input type="hidden" name="id" value={item.id} /><button className="button button-danger">Delete item</button></form></details>)}</div></div>;
}
